language: generic

env:
  global:
    - secure: "clCFM3prHnDocZ8lXlimPxAogvFirD1Zx8cMcFJ/XpkTA/0pCgnhpArM4y/NzLHR57pNZTSCr3p6XZI1c1iTG4Zm8x0sK2A4aTFRahypXNy/e+LzAbtd1y1+dEEDwlJvNNGxizQX4frhOgSNQFDFnWLtmF3stlft5YWyc2kI+FI="
    - secure: "jKJErCng8Sk8YJ0IN2FX3lhv7G1LeudMfFBAXViZaXn8w/gWPs+SlfXQmIJ5SruU7U2GQKnAhzbjwXjVAgAh8OAblzny0DDm5Lh5WmwkgAP8JH1LpsBwCYx2S/v8qyR4DX1RVhHS8mQu298180ZDVgGccw+hd8xrE/S5TEQcNfQ="

addons:
    apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - libstdc++-5-dev

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: linux
      sudo: false

install:
- |
  if [[ ${MASON_PLATFORM:-unset} == 'unset' ]] || [[ ${MASON_PLATFORM} == 'osx' ]] || [[ ${MASON_PLATFORM} == 'linux' ]]; then
    echo "Installing clang for OSX/Linux via 'install' target"
    source utils/toolchain.sh
    which ${CC}
    ${CC} -v
    which ${CXX}
    ${CXX} -v
  fi

script:
- ./test/all.sh
