language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: linux
      sudo: false
    - os: linux
      sudo: false
      addons:
        apt:
          packages:
           - wget
    - os: linux
      sudo: false
      addons: *libstdcpp5
        apt:
          packages:
           - wget

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
